config/routes.rb
Rails.application.routes.draw do

  root 'index#index'

  resources :block_lists, except: :show, path: 'blocklists'
  get    '/blocklists/'                     => 'block_lists#index'
  get    '/blocklists/:id'                  => 'block_lists#show', :constraints => { :id => /[0-9]+/ }, :as => :block_list_path
  get    '/blocklists/:name'                => 'block_lists#show'
  post   '/blocklists/:id/add/blocker'      => 'block_lists#add_blocker', :as => :add_blocker
  post   '/blocklists/:id/add/admin'        => 'block_lists#add_admin', :as => :add_admin
  delete '/blocklists/:id/remove/blocker/'  => 'block_lists#remove_blocker', :as => :remove_blocker
  post   '/blocklists/:id/subscribe'        => 'block_lists#subscribe', :as => :list_subscribe
  delete '/blocklists/:id/subscribe'        => 'block_lists#unsubscribe', :as => :list_unsubscribe

  post   '/reports/:id/approve' => 'reports#approve', :as => :report_approve
  get    '/reports/new'         => 'reports#new',     :as => :report_new
  get    '/reports/:id'         => 'reports#show',    :as => :report
  delete '/reports/:id'         => 'reports#deny',    :as => :report_deny
  post   '/reports'             => 'reports#create',  :as => :report_create
  get    '/reports'             => 'reports#index',   :as => :reports

  get  '/tools/hunkerdown'  => 'tools#hunkerdown'
  get  '/tools/blockchain'  => 'tools#blockchain'
  post '/tools/blockchain'  => 'tools#blockchain_perform'
  get  '/unblocker'         => redirect('/tools/unblocker')
  get  '/tools/unblocker'   => 'tools#unblocker'
  post '/tools/unblocker'   => 'tools#unblocker_perform',   :as => :unblocker_perform

  get     '/login'                   => redirect('/auth/twitter')
  get     '/signin'                  => redirect('/auth/twitter')
  delete  '/signout'                 => 'sessions#destroy',  :as => :signout
  get     '/auth/failure'            => 'sessions#failure'
  get     '/auth/:provider/callback' => 'sessions#create'

  get '/profile' => 'users#index', :as => :profile
  get '/user/reports' => 'users#reports', :as => :user_reports

  require "sidekiq/web"
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/block_list.rb
class BlockList < ActiveRecord::Base
  has_many :reports
  has_many :blocks

  has_many :subscriptions
  has_many :users, through: :subscriptions

  has_many :active_reports, -> { where(approved: true, expired: false) }, class_name: Report
  has_many :targets, through: :active_reports

  has_many :admin_records, class_name: Admin, dependent: :destroy
  has_many :admins, through: :admin_records, source: :user, dependent: :destroy

  has_many :blocker_records, class_name: Blocker, dependent: :destroy
  has_many :blockers, through: :blocker_records, source: :user, dependent: :destroy

  validates :name, presence: true, uniqueness: {case_sensitive: false}


  def blocker?(user)
    user.in? self.blockers
  end


  def admin?(user)
    user.in? self.admins
  end


  def self.where_blocker(user)
    self.joins(:blocker_records).where(:blockers => {user_id: user.id})
  end


  def self.where_admin(user)
    self.joins(:admin_records).where(:admins => {user_id: user.id})
  end


  def blocker_autoapprove?(user)
    (self.autoapprove_blocker?) and (self.blocker? user)
  end


  def admin_autoapprove?(user)
    (self.autoapprove_admin?) and (self.admin? user)
  end


  def add_admin(user, authorized_by: nil, list_recently_created: nil)
    if (self.admin? authorized_by) or (list_recently_created)
      Admin.find_or_create_by(user: user, block_list: self)
      user.update_log("Became admin of block list #{self.name}")
    end
  end


  def add_blocker(user, authorized_by)
    if self.admin? authorized_by
      Blocker.find_or_create_by(user: user, block_list: self)
      user.update_log("Became blocker of block list #{self.name}")
    end
  end


  def remove_admin(user, authorized_by)
    if (user.id == authorized_by.id) or (self.admin? authorized_by)
      Admin.find_by(user: user, block_list: self).delete
      user.update_log("Removed as admin for block list #{self.name}")
    end
  end


  def remove_blocker(user, authorized_by)
    if (user.id == authorized_by.id) or (self.admin? authorized_by)
      Blocker.find_by(user: user, block_list: self).delete
      user.update_log("Removed as blocker for block list #{self.name}")
    end
  end


  def subscribe(user)
    CreateBlocksFromSubscribe.perform_async(user.id, self.id)
    Subscription.find_or_create_by(user: user, block_list: self)
    user.update_log("Subscribed to block list #{self.name}")
  end


  def unsubscribe(user)
    CreateUnblocksFromUnsubscribe.perform_async(user.id, self.id)
    Subscription.find_by(user: user, block_list: self).delete
    user.update_log("Un-subscribed from block list #{self.name}")
  end


  def self.make(name:, user:, description: nil, expires: 365, private_list: false, showcase: false)
    block_list = self.find_or_create_by(
      name: name
    )
    block_list.update_attributes(
      expires: expires,
      private_list: private_list,
      description: description,
      showcase: showcase,
    )
    user.update_log("Created block_list #{block_list.name}")

    block_list.add_admin(user, list_recently_created: true)
    block_list.subscribe(user)

    block_list
  end


  def self.get_expiration(block_list)
    block_list.expires ? DateTime.now + block_list.expires : nil
  rescue NoMethodError
    nil
  end


  def self.find_by_name(name)
    name = Utils.strip_if_leading_character(name, '#')
    self.where("replace(lower(name), ' ', '') = ?", name.downcase).first
  end


end

app/controllers/block_lists_controller.rb
class BlockListsController < ApplicationController
  before_action :set_block_list

  # GET /block_lists
  def index
    @block_lists = BlockList.all.limit(30)
  end

  # GET /block_lists/1
  def show
    if @block_list.private_list? and not @block_list.blocker? current_user
      redirect_to request.env["HTTP_REFERER"] || root_url, notice: 'Not authorized'
    end
  end

  # GET /block_lists/new
  def new
    if current_user
      @block_list = BlockList.new
    else
      redirect_to '/'
    end
  end

  # POST /block_list
  def create
    if current_user
      @block_list = BlockList.make(block_list_params['name'], current_user)

      respond_to do |format|
        if @block_list.save
          format.html { redirect_to block_list_url(@block_list), notice: 'Block List created' }
        else
          format.html { render :new }
        end
      end
    else
      redirect_to :back
    end
  end

  # PATCH/PUT /block_lists/1
  def update
    if @block_list.admin? current_user
      respond_to do |format|
        if @block_list.update(block_list_params)
          format.html { redirect_to @block_list, notice: 'Block list was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end
  end

  # POST /block_lists/1/subscribe
  def subscribe
    if current_user
      Subscription.add(current_user, @block_list)

      respond_to do |format|
        format.html { redirect_to :back, notice: 'Subscribed to '+@block_list.name}
      end

    else
      redirect_to :back
    end
  end

  # DELETE /block_lists/1/subscribe
  def unsubscribe
    if current_user
      Subscription.remove(current_user, @block_list)

      respond_to do |format|
        format.html { redirect_to :back, notice: 'Unsubscribed from '+@block_list.name}
      end

    else
      redirect_to :back
    end
  end

  # POST /block_lists/1/add/blocker
  def add_blocker
    if @block_list.admin? current_user
      blocker = Blocker.create(block_list: @block_list, user: User.get_from_twitter_name(params[:user_name]))

      if blocker.save
        notice = "Blocker #{params[:user_name]} added"
      else
        notice = blocker.errors.full_messages
      end

      redirect_to :back, notice: notice
    else
      redirect_to :back, notice: 'Not authorized'
    end
  end

  # POST /block_lists/1/add/admin
  def add_admin
    if @block_list.admin? current_user
      admin = Admin.create(block_list: @block_list, user: User.get_from_twitter_name(params[:user_name]))

      if admin.save
        notice = "Admin #{params[:user_name]} added"
      else
        notice = admin.errors.full_messages
      end

      redirect_to :back, notice: notice
    else
      redirect_to :back, notice: 'Not authorized'
    end
  end

  def remove_blocker
    target_id = params[:user_id].keys[0].to_i
    if (@block_list.admin? current_user) or (current_user.id == target_id)
      Blocker.find_by(block_list: @block_list, user: User.find(target_id)).delete
      redirect_to :back, notice: 'Removed!'
    else
      redirect_to :back, notice: 'Not authorized'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_block_list
      if params[:id]
        @block_list = BlockList.find(params[:id])
      elsif params[:name]
        @block_list = BlockList.where("lower(name) = ?", params[:name].downcase).first
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def block_list_params
      params.require(:block_list).permit(:name)
    end
end

app/views/block_lists/_form.html.haml
= form_for @block_list, :html => { :class => "form-horizontal block_list" } do |f|
  - if @block_list.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        %h3.panel-title
          = pluralize(@block_list.errors.count, "error")
          prohibited this block_list from being saved:
      .panel-body
        %ul
          - @block_list.errors.full_messages.each do |msg|
            %li= msg
  .form-group
    = f.label :name, :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, :class => 'form-control'
    = f.error_span(:name)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), |
        block_lists_path, :class => 'btn btn-default'                |

app/views/block_lists/edit.html.haml
- model_class = BlockList
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/block_lists/index.html.haml
- model_class = BlockList
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th Name
      %th Description
      %th Blockers
      %th Blocked Users
      %th Actions
  %tbody
    - @block_lists.where(showcase: true).each do |block_list|
      %tr
        %td= link_to block_list.name, block_list_path(block_list)
        %td= block_list.description
        %td= block_list.blockers.length
        %td= block_list.targets.length
        %td
          - if current_user.in? block_list.users
            = button_to 'Unsubscribe + Remove Blocks',
              list_unsubscribe_path(block_list),
              :method => :delete,
              :class => 'btn btn-sm btn-danger'
          - else
            = button_to 'Subscribe',
              list_subscribe_path(block_list),
              :method => :post,
              :class => 'btn btn-sm btn-primary'

= link_to 'Create new Block List',
  '/blocklists/new', :class => 'btn btn-default'

app/views/block_lists/new.html.haml
- model_class = BlockList
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/block_lists/show.html.haml
- model_class = BlockList
.page-header
  %h1= @block_list.name
  %p= @block_list.description
  - if current_user.in? @block_list.users
    = link_to 'Unsubscribe + Remove Blocks',
      list_unsubscribe_path(@block_list),
      :method => :delete,
      :class => 'btn btn-danger'
  - else
    = link_to 'Subscribe',
      list_subscribe_path(@block_list),
      :method => :post,
      :class => 'btn btn-primary'

- if @block_list.blocker? current_user
  %p Only active reports are shown here. Go to <a href='/reports'>reports</a> to view pending reports
  %p Blockers are allowed to approve / deny reports. Admins have all the capabilities of blockers, while also being allowed to add/remove blockers/admins.
  %hr

%dl.dl-horizontal
  %dt
    %strong Subscribers:
  %dd= @block_list.users.length
  - if @block_list.admins.length > 0
    %dt
      %strong Admins:
    - for admin in @block_list.admins
      %dd
        = link_to "#{admin.name} (@#{admin.user_name})", "http://#{admin.website}.com/#{admin.user_name}"
        - if current_user.id == admin.id
          = form_tag remove_blocker_path(@block_list), :method => 'delete', :class => 'delete-button' do
            = submit_tag 'x',
              :title => 'Removes this admin',
              :data  => { :confirm => 'Remove this admin?'}
            = hidden_field :user_id, admin.id

  - if (@block_list.blockers - @block_list.admins).length > 0
    %dt
      %strong Blockers:
    - for blocker in (@block_list.blockers - @block_list.admins)
      %dd
        = link_to "#{blocker.name} (@#{blocker.user_name})", "http://#{blocker.website}.com/#{blocker.user_name}"
        - if (@block_list.admin? current_user) or (current_user.id == blocker.id)
          = form_tag remove_blocker_path(@block_list), :method => 'delete', :class => 'delete-button' do
            = submit_tag 'x',
              :title => 'Removes this blocker',
              :data  => { :confirm => 'Remove this blocker?'}
            = hidden_field :user_id, blocker.id

  %dt
    %strong Blocked Users:
  %dd= @block_list.targets.length
  - if @block_list.blocker? current_user
    %br
    %dt
      %strong Pending Reports:
    %dd= link_to @block_list.reports.where(processed: false).length, '/reports'
    %dt
      %strong Active Blocks:
    %dd= @block_list.blocks.length

%dl.dl-horizontal
  - if @block_list.admin? current_user
    = form_tag add_blocker_path(@block_list), :method => 'post' do
      %dt= submit_tag "Add Blocker", :class => 'btn btn-primary btn-sm'
      %dd= text_field_tag :user_name, nil, :placeholder => "@name, like @lynncyrin"
    = form_tag add_admin_path(@block_list), :method => 'post' do
      %dt= submit_tag "Add Admin", :class => 'btn btn-primary btn-sm'
      %dd= text_field_tag :user_name, nil, :placeholder => "@name, like @lynncyrin"

%h2 Active Reports
%table.table.table-striped
  %thead
    %tr
      %th Username
      %th Profile Description
      %th Time Reported
      %th View Reports
  %tbody
    - @block_list.reports.active.limit(100).each do |report|
      %tr
        %td= link_to "#{report.target.name} (@#{report.target.user_name})", "http://twitter.com/#{report.target.user_name}"
        %td= report.target.description
        %td= time_ago_in_words(report.created_at) + ' ago'
        %td= link_to 'Reports', "/user/reports/?id=#{report.target.id}", :class => 'btn btn-default'
      - if report.children.count > 0
        %tr
          %td -
          %td= "the above report has #{report.children.count} other reports attached to it"
          %td -
          %td -
  - if @block_list.reports.active.count > 100
    %p (list has more than 100 blocked users)

/ = link_to 'Back to Block Lists',
/   block_lists_path, :class => 'btn btn-default'
/ = link_to 'Create new Block List',
/   '/blocklists/new', :class => 'btn btn-default'

.spacer