config/routes.rb
Rails.application.routes.draw do

  root 'index#index'

  resources :block_lists, except: :show, path: 'blocklists'
  get    '/blocklists/'                     => 'block_lists#index'
  get    '/blocklists/:id'                  => 'block_lists#show', :constraints => { :id => /[0-9]+/ }, :as => :block_list_path
  get    '/blocklists/:name'                => 'block_lists#show'
  post   '/blocklists/:id/add/blocker'      => 'block_lists#add_blocker', :as => :add_blocker
  post   '/blocklists/:id/add/admin'        => 'block_lists#add_admin', :as => :add_admin
  delete '/blocklists/:id/remove/blocker/'  => 'block_lists#remove_blocker', :as => :remove_blocker
  post   '/blocklists/:id/subscribe'        => 'block_lists#subscribe', :as => :list_subscribe
  delete '/blocklists/:id/subscribe'        => 'block_lists#unsubscribe', :as => :list_unsubscribe

  post   '/reports/:id/approve' => 'reports#approve', :as => :report_approve
  get    '/reports/new'         => 'reports#new',     :as => :report_new
  get    '/reports/:id'         => 'reports#show',    :as => :report
  delete '/reports/:id'         => 'reports#deny',    :as => :report_deny
  post   '/reports'             => 'reports#create',  :as => :report_create
  get    '/reports'             => 'reports#index',   :as => :reports

  get  '/tools/hunkerdown'  => 'tools#hunkerdown'
  get  '/tools/blockchain'  => 'tools#blockchain'
  post '/tools/blockchain'  => 'tools#blockchain_perform'
  get  '/unblocker'         => redirect('/tools/unblocker')
  get  '/tools/unblocker'   => 'tools#unblocker'
  post '/tools/unblocker'   => 'tools#unblocker_perform',   :as => :unblocker_perform

  get     '/login'                   => redirect('/auth/twitter')
  get     '/signin'                  => redirect('/auth/twitter')
  delete  '/signout'                 => 'sessions#destroy',  :as => :signout
  get     '/auth/failure'            => 'sessions#failure'
  get     '/auth/:provider/callback' => 'sessions#create'

  get '/profile' => 'users#index', :as => :profile
  get '/user/reports' => 'users#reports', :as => :user_reports

  require "sidekiq/web"
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :block_list
  belongs_to :reporter, class_name: User
  belongs_to :target, class_name: User
  belongs_to :approver, class_name: User
  has_many :blocks

  belongs_to :parent, class_name: self
  has_many :children, class_name: self, foreign_key: :parent_id

  validates :reporter, presence: true
  validates_presence_of :block_list,
    message: "Must include a valid block list"
  validates_presence_of :text,
    message: 'Report cannot be blank'
  validates_presence_of :target,
    message: "Need to specify who to report with \"+USERNAME\""
  validates_uniqueness_of :text, scope: [:block_list, :reporter, :target,],
    message: "You have already created this report"

  scope :pending, -> { where(processed: false) }
  scope :active, -> { where(approved: true, expired: false) }
  scope :denied, -> { where(processed: true, approved: false) }

  def child?
    self.parent_id != 1
  end

  def self.visible(user)
    if user == nil
      self.none
    else
      self.joins(:block_list => :blockers).where(:blockers => {user_id: user.id})
    end
  end

  def self.parse_regex(text:, reporter:)
  # text -> string ("+lynncyrin #cats")
  # reporter -> User

    match_target = text.match('(?<=\+)\@*\w*')
    target = match_target ? User.get_from_twitter_name(match_target[0]) : nil

    match_list = text.match('(?<=\#)\w*')
    block_list = match_list ? BlockList.find_by_name(match_list[0]) : nil

    self.parse_objects(
      block_list: block_list,
      target:     target,
      text:       text,
      reporter:   reporter,
    )

  end

  def self.parse_text_args(block_list:, target:, text:, reporter:)
  # block_list -> string ("cats")
  # target -> string ("lynncyrin")
  # text -> string ("knocked my mouse off the desk")
  # reporter -> User

    self.parse_objects(
      block_list: BlockList.find_by_name(block_list),
      target:     User.get_from_twitter_name(target),
      text:       text,
      reporter:   reporter,
    )
  end

  def self.parse_objects(block_list:, target:, text:, reporter:, parent_id: 1)
  # block_list -> BlockList
  # target -> User
  # text -> string
  # reporter -> User

    expires = BlockList.get_expiration(block_list)

    report = self.find_or_create_by(
      text: text,
      block_list: block_list,
      reporter: reporter,
      target: target,
    )
    report.update_attributes(
      expires: expires,
      parent_id: parent_id,
    )

    report.reporter.increment(:reports_created)
    report.target.increment(:times_reported)
    report.process_child
    report.autoapprove

    report
  end

  def process_child
    if self.child? then self.update_attributes(processed: true, approved: true) end
  end

  def autoapprove
    if not (self.processed? or self.child?)
      if (self.block_list.blocker_autoapprove? self.reporter) or (self.block_list.admin_autoapprove? self.reporter)
        self.approve(self.reporter)
      end
    end
  rescue NoMethodError
  end

  def approve(approver)
    if (approver.in? self.block_list.blockers) and not (self.processed? or self.child?)
      # temporarily disabled pending a rewrite
      # CreateBlocksFromReport.perform_async(self.id)
      self.update_attributes(approver: approver, approved: true, processed: true)
      self.target.increment(:times_blocked)
      self.reporter.increment(:reports_approved)
    else
      logger.info { "User(#{approver.id}) Not Authorized to approve Report(#{self.id})" }
    end
  end

  def deny(approver)
    if (approver.in? self.block_list.blockers) and (not self.processed?)
      self.update_attributes(processed: true)
    else
      logger.info { "User(#{approver.id}) Not Authorized to deny Report(#{self.id})" }
    end
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:approve, :deny, :show]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all.visible(current_user).limit(100)
  end

  # GET /reports/1
  def show
  end

  # GET /reports/new
  def new
    if current_user
      @report = Report.new
    else
      redirect_to '/'
    end
  end

  # POST /reports
  # POST /reports.json
  def create
    if current_user
      @report = Report.parse_regex(
        text:     report_params['text'],
        reporter: current_user,
      )

      respond_to do |format|
        if @report.save
          format.html { redirect_to '/reports/new', notice: 'Report was successfully created' }
        else
          format.html { render :new }
        end
      end
    else
      redirect_to '/'
    end
  end

  # POST /reposts/1
  def approve
    if @report.block_list.blocker? current_user
      @report.approve(current_user)

      respond_to do |format|
        format.html { redirect_to reports_url, notice: 'Report approved' }
      end
    else
      redirect_to :back
    end
  end

  # DELETE /reports/1
  def deny
    if @report.block_list.blocker? current_user
      @report.deny(current_user)

      respond_to do |format|
        format.html { redirect_to reports_url, notice: 'Report denied' }
      end
    else
      redirect_to :back
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.where(id: params[:id]).visible(current_user).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:text)
    end
end

app/views/reports/index.html.haml
- model_class = Report
<script type="text/javascript" async src="https://platform.twitter.com/widgets.js"></script>

- unless params['show_processed']
  - @reports = @reports.where(processed: false)

- if (@reports.where(processed: false).length == 0) and (not params['show_processed'])
  .page-header
    %h1 All Reports Processed!

  - if not params['show_processed']
    = link_to 'Create new report', '/reports/new', :class => 'btn btn-default'
    = link_to 'Show processed reports', '/reports/?show_processed=true', :class => 'btn btn-default'

- elsif @reports.length > 0

  .page-header
    %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize

  = link_to 'Create new report', '/reports/new', :class => 'btn btn-default'
  - if not params['show_processed']
    = link_to 'Show processed reports', '/reports/?show_processed=true', :class => 'btn btn-default'
  - else
    = link_to 'Hide processed reports', '/reports', :class => 'btn btn-default'

  %hr
  %p This is an administrative area, showing reports that need to be processed or approved.

  %table.table.table-striped
    %thead
      %tr
        %th= 'Report'
        %th= model_class.human_attribute_name(:created_at)
        %th= 'Reporter'
        %th= 'Target User'
        %th Block List
        %th= t '.actions', :default => t("helpers.actions")
    %tbody
      - @reports.each do |report|
        %tr
          %td= link_to report.text, report_url(report.id)
          %td= time_ago_in_words(report.created_at) + ' ago'
          %td
            = link_to report.reporter.name+' (@'+report.reporter.user_name+')',
              "https://twitter.com/"+report.reporter.user_name
          %td
            = link_to report.target.name+' (@'+report.target.user_name+')',
              "https://twitter.com/"+report.target.user_name

          - block_list = BlockList.find(report.block_list_id)
          %td= link_to block_list.name, block_list_url(block_list)

          - unless report.processed
            %td
              = button_to 'Approve',
                report_approve_path(report),
                :method => :post,
                :class => 'btn btn-xs btn-primary'
              = button_to 'Deny',
                report_deny_path(report),
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-xs btn-danger'
          - else
            %td -

- else
  .page-header
    %h1 No Accessible Reports

app/views/reports/new.html.haml
- model_class = Report
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= form_for @report, :html => { :class => "form-horizontal report" } do |f|
  - if @report.errors.any?
    #error_expl.panel.panel-danger
      .panel-heading
        %h3.panel-title
          = pluralize(@report.errors.count, "error")
          prohibited this report from being saved:
      .panel-body
        %ul
          - @report.errors.messages.values.each do |msg|
            - msg.each do |m|
              %li= msg[0]
  .description
    %p Create a new report for a block list. Reports have to be formatted like:
    %p
      %code #BlockListName +ThePersonToBlock a description of why you are blocking them
    %p Example:
    %p
      %code #TerribleCompanies +SallieMae exports millions of students with loans
    %p Many block lists will also require reports to be approved by an administrator before that become blocks
  %hr
  .form-group
    = f.label 'Enter Report:', :class => 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :text, :class => 'form-control'
    = f.error_span(:text)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil, :value => 'Create', :class => 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")),
        reports_path, :class => 'btn btn-default'

app/views/reports/show.html.haml
- model_class = Report
- if @report == nil
  .page-header
    %h1 Report not accessible
- else
  .page-header
    %h1= t '.title', :default => model_class.model_name.human.titleize
  %dl.dl-horizontal
    %dt
      %strong
        = model_class.human_attribute_name(:text)
        \:
    %dd= @report.text
    %dt= link_to t('.back', :default => t("helpers.links.back")),
      reports_path, :class => 'btn btn-default'