config/routes.rb
Rails.application.routes.draw do

  root 'index#index'

  resources :block_lists, except: :show, path: 'blocklists'
  get    '/blocklists/'                     => 'block_lists#index'
  get    '/blocklists/:id'                  => 'block_lists#show', :constraints => { :id => /[0-9]+/ }, :as => :block_list_path
  get    '/blocklists/:name'                => 'block_lists#show'
  post   '/blocklists/:id/add/blocker'      => 'block_lists#add_blocker', :as => :add_blocker
  post   '/blocklists/:id/add/admin'        => 'block_lists#add_admin', :as => :add_admin
  delete '/blocklists/:id/remove/blocker/'  => 'block_lists#remove_blocker', :as => :remove_blocker
  post   '/blocklists/:id/subscribe'        => 'block_lists#subscribe', :as => :list_subscribe
  delete '/blocklists/:id/subscribe'        => 'block_lists#unsubscribe', :as => :list_unsubscribe

  post   '/reports/:id/approve' => 'reports#approve', :as => :report_approve
  get    '/reports/new'         => 'reports#new',     :as => :report_new
  get    '/reports/:id'         => 'reports#show',    :as => :report
  delete '/reports/:id'         => 'reports#deny',    :as => :report_deny
  post   '/reports'             => 'reports#create',  :as => :report_create
  get    '/reports'             => 'reports#index',   :as => :reports

  get  '/tools/hunkerdown'  => 'tools#hunkerdown'
  get  '/tools/blockchain'  => 'tools#blockchain'
  post '/tools/blockchain'  => 'tools#blockchain_perform'
  get  '/unblocker'         => redirect('/tools/unblocker')
  get  '/tools/unblocker'   => 'tools#unblocker'
  post '/tools/unblocker'   => 'tools#unblocker_perform',   :as => :unblocker_perform

  get     '/login'                   => redirect('/auth/twitter')
  get     '/signin'                  => redirect('/auth/twitter')
  delete  '/signout'                 => 'sessions#destroy',  :as => :signout
  get     '/auth/failure'            => 'sessions#failure'
  get     '/auth/:provider/callback' => 'sessions#create'

  get '/profile' => 'users#index', :as => :profile
  get '/user/reports' => 'users#reports', :as => :user_reports

  require "sidekiq/web"
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end if Rails.env.production?
  mount Sidekiq::Web, at: "/sidekiq"

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title TheBlockBot
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    /[if lt IE 9]
      %script{:src => "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js", :type =>"text/javascript"}
  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav.container-fluid

            %a.navbar-brand{:href => "/"} TheBlockBot

            / %li= link_to "Block Lists", "/blocklists"

            %li.dropdown
              %a#toolMenu.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
                Tools
                %span.caret
              %ul.dropdown-menu{"aria-labelledby" => "toolMenu"}
                %li= link_to "Remove All Blocks", "/tools/unblocker"
                %li= link_to "Twitter Block Chain", "/tools/blockchain"

            - if current_user
              / - if current_user.is_blocker
              /   %li= link_to "Reports",   "/reports"

              %li.pull-right= link_to 'Sign out', signout_path, method: 'delete'
              %li.pull-right= link_to 'Profile', '/profile'
              %li.pull-right.login(title="You!")
                %span.name= current_user.name
                %img.avatar(src="#{current_user.profile_image_url}")

            - else
              %li.pull-right= link_to "Sign in with Twitter", '/auth/twitter'
    .container
      %main.row
        .col-lg-12
          = bootstrap_flash
          = yield
    %footer
      .container
        %p
          :markdown
            A [CollectQT](https://www.patreon.com/collectqt) Project, contact [@lynncyrin](https://twitter.com/lynncyrin) for issues